INSERT INTO countries (name, alpha2_code, alpha3_code, numeric_code, capital, currency, continent)
VALUES
('Afghanistan', 'AF', 'AFG', 4, 'Kabul', 'Afghan afghani', 'Asia'),
('Albania', 'AL', 'ALB', 8, 'Tirana', 'Albanian lek', 'Europe'),
('Algeria', 'DZ', 'DZA', 12, 'Algiers', 'Algerian dinar', 'Africa'),
('Andorra', 'AD', 'AND', 20, 'Andorra la Vella', 'Euro', 'Europe'),
('Angola', 'AO', 'AGO', 24, 'Luanda', 'Angolan kwanza', 'Africa'),
('Antigua and Barbuda', 'AG', 'ATG', 28, 'St. Johns', 'Eastern Caribbean dollar', 'North America'),
('Argentina', 'AR', 'ARG', 32, 'Buenos Aires', 'Argentine peso', 'South America'),
('Armenia', 'AM', 'ARM', 51, 'Yerevan', 'Armenian dram', 'Asia'),
('Australia', 'AU', 'AUS', 36, 'Canberra', 'Australian dollar', 'Oceania'),
('Austria', 'AT', 'AUT', 40, 'Vienna', 'Euro', 'Europe'),
('Azerbaijan', 'AZ', 'AZE', 31, 'Baku', 'Azerbaijani manat', 'Asia'),
('Bahamas', 'BS', 'BHS', 44, 'Nassau', 'Bahamian dollar', 'North America'),
('Bahrain', 'BH', 'BHR', 48, 'Manama', 'Bahraini dinar', 'Asia'),
('Bangladesh', 'BD', 'BGD', 50, 'Dhaka', 'Bangladeshi taka', 'Asia'),
('Barbados', 'BB', 'BRB', 52, 'Bridgetown', 'Barbadian dollar', 'North America'),
('Belarus', 'BY', 'BLR', 112, 'Minsk', 'Belarusian ruble', 'Europe'),
('Belgium', 'BE', 'BEL', 56, 'Brussels', 'Euro', 'Europe'),
('Belize', 'BZ', 'BLZ', 84, 'Belmopan', 'Belize dollar', 'North America'),
('Benin', 'BJ', 'BEN', 204, 'Porto-Novo', 'West African CFA franc', 'Africa'),
('Bermuda', 'BM', 'BMU', 60, 'Hamilton', 'Bermudian dollar', 'North America'),
('Bhutan', 'BT', 'BTN', 64, 'Thimphu', 'Bhutanese ngultrum', 'Asia'),
('Bolivia (Plurinational State of)', 'BO', 'BOL', 68, 'La Paz', 'Bolivian boliviano', 'South America'),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535, '', 'United States dollar', 'North America'),
('Bosnia and Herzegovina', 'BA', 'BIH', 70, 'Sarajevo', 'Bosnia and Herzegovina convertible mark', 'europe')
('Botswana', 'BW', 'BWA', 72, 'Gaborone', 'Botswana pula', 'Africa'),
('Brazil', 'BR', 'BRA', 76, 'Brasília', 'Brazilian real', 'South America'),
('Brunei Darussalam', 'BN', 'BRN', 96, 'Bandar Seri Begawan', 'Brunei dollar', 'Asia'),
('Bulgaria', 'BG', 'BGR', 100, 'Sofia', 'Bulgarian lev', 'Europe'),
('Burkina Faso', 'BF', 'BFA', 854, 'Ouagadougou', 'West African CFA franc', 'Africa'),
('Burundi', 'BI', 'BDI', 108, 'Bujumbura', 'Burundian franc', 'Africa'),
('Cabo Verde', 'CV', 'CPV', 132, 'Praia', 'Cape Verdean escudo', 'Africa'),
('Cambodia', 'KH', 'KHM', 116, 'Phnom Penh', 'Cambodian riel', 'Asia'),
('Cameroon', 'CM', 'CMR', 120, 'Yaoundé', 'Central African CFA franc', 'Africa'),
('Canada', 'CA', 'CAN', 124, 'Ottawa', 'Canadian dollar', 'North America'),
('Central African Republic', 'CF', 'CAF', 140, 'Bangui', 'Central African CFA franc', 'Africa'),
('Chad', 'TD', 'TCD', 148, 'N Djamena', 'Central African CFA franc', 'Africa'),
('Chile', 'CL', 'CHL', 152, 'Santiago', 'Chilean peso', 'South America'),
('China', 'CN', 'CHN', 156, 'Beijing', 'Renminbi', 'Asia'),
('Colombia', 'CO', 'COL', 170, 'Bogotá', 'Colombian peso', 'South America'),
('Comoros', 'KM', 'COM', 174, 'Moroni', 'Comorian franc', 'Africa'),
('Congo', 'CG', 'COG', 178, 'Brazzaville', 'Central African CFA franc', 'Africa'),
('Congo (Democratic Republic of the)', 'CD', 'COD', 180, 'Kinshasa', 'Congolese franc', 'Africa'),
('Costa Rica', 'CR', 'CRI', 188, 'San José', 'Costa Rican colón', 'North America'),
('Côte d Ivoire', 'CI', 'CIV', 384, 'Yamoussoukro', 'West African CFA franc', 'Africa'),
('Croatia', 'HR', 'HRV', 191, 'Zagreb', 'Croatian kuna', 'Europe'),
('Cuba', 'CU', 'CUB', 192, 'Havana', 'Cuban peso', 'North America'),
('Curaçao', 'CW', 'CUW', 531, '', 'Netherlands Antillean guilder', 'North America'),
('Cyprus', 'CY', 'CYP', 196, 'Nicosia', 'Euro', 'Asia'),
('Czechia', 'CZ', 'CZE', 203, 'Prague', 'Czech koruna', 'Europe'),
('Denmark', 'DK', 'DNK', 208, 'Copenhagen', 'Danish krone', 'Europe'),
('Djibouti', 'DJ', 'DJI', 262, 'Djibouti', 'Djiboutian franc', 'Africa'),
('Dominica', 'DM', 'DMA', 212, 'Roseau', 'Eastern Caribbean dollar', 'North America'),
('Dominican Republic', 'DO', 'DOM', 214, 'Santo Domingo', 'Dominican peso', 'North America'),
('Ecuador', 'EC', 'ECU', 218, 'Quito', 'United States dollar', 'South America'),
('Egypt', 'EG', 'EGY', 818, 'Cairo', 'Egyptian pound', 'Africa'),
('El Salvador', 'SV', 'SLV', 222, 'San Salvador', 'United States dollar', 'North America'),
('Equatorial Guinea', 'GQ', 'GNQ', 226, 'Malabo', 'Central African CFA franc', 'Africa'),
('Eritrea', 'ER', 'ERI', 232, 'Asmara', 'Eritrean nakfa', 'Africa'),
('Estonia', 'EE', 'EST', 233, 'Tallinn', 'Euro', 'Europe'),
('Eswatini', 'SZ', 'SWZ', 748, 'Lobamba', 'Swazi lilangeni', 'Africa'),
('Ethiopia', 'ET', 'ETH', 231, 'Addis Ababa', 'Ethiopian birr', 'Africa'),
('Fiji', 'FJ', 'FJI', 242, 'Suva', 'Fijian dollar', 'Oceania'),
('Finland', 'FI', 'FIN', 246, 'Helsinki', 'Euro', 'Europe'),
('France', 'FR', 'FRA', 250, 'Paris', 'Euro', 'Europe'),
('Gabon', 'GA', 'GAB', 266, 'Libreville', 'Central African CFA franc', 'Africa'),
('Gambia', 'GM', 'GMB', 270, 'Banjul', 'Gambian dalasi', 'Africa'),
('Georgia', 'GE', 'GEO', 268, 'Tbilisi', 'Georgian lari', 'Asia'),
('Germany', 'DE', 'DEU', 276, 'Berlin', 'Euro', 'Europe'),
('Ghana', 'GH', 'GHA', 288, 'Accra', 'Ghanaian cedi', 'Africa'),
('Greece', 'GR', 'GRC', 300, 'Athens', 'Euro', 'Europe'),
('Grenada', 'GD', 'GRD', 308, 'St. Georges', 'Eastern Caribbean dollar', 'North America'),
('Guatemala', 'GT', 'GTM', 320, 'Guatemala City', 'Guatemalan quetzal', 'North America'),
('Guinea', 'GN', 'GIN', 324, 'Conakry', 'Guinean franc', 'Africa'),
('Guinea-Bissau', 'GW', 'GNB', 624, 'Bissau', 'West African CFA franc', 'Africa'),
('Guyana', 'GY', 'GUY', 328, 'Georgetown', 'Guyanese dollar', 'South America'),
('Haiti', 'HT', 'HTI', 332, 'Port-au-Prince', 'Haitian gourde', 'North America'),
('Honduras', 'HN', 'HND', 340, 'Tegucigalpa', 'Honduran lempira', 'North America'),
('Hungary', 'HU', 'HUN', 348, 'Budapest', 'Hungarian forint', 'Europe'),
('Iceland', 'IS', 'ISL', 352, 'Reykjavik', 'Icelandic króna', 'Europe'),
('India', 'IN', 'IND', 356, 'New Delhi', 'Indian rupee', 'Asia'),
('Indonesia', 'ID', 'IDN', 360, 'Jakarta', 'Indonesian rupiah', 'Asia'),
('Iran (Islamic Republic of)', 'IR', 'IRN', 364, 'Tehran', 'Iranian rial', 'Asia'),
('Iraq', 'IQ', 'IRQ', 368, 'Baghdad', 'Iraqi dinar', 'Asia'),
('Ireland', 'IE', 'IRL', 372, 'Dublin', 'Euro', 'Europe'),
('Israel', 'IL', 'ISR', 376, 'Jerusalem', 'Israeli new shekel', 'Asia'),
('Italy', 'IT', 'ITA', 380, 'Rome', 'Euro', 'Europe'),
('Jamaica', 'JM', 'JAM', 388, 'Kingston', 'Jamaican dollar', 'North America'),
('Japan', 'JP', 'JPN', 392, 'Tokyo', 'Japanese yen', 'Asia'),
('Jordan', 'JO', 'JOR', 400, 'Amman', 'Jordanian dinar', 'Asia'),
('Kazakhstan', 'KZ', 'KAZ', 398, 'Nur-Sultan', 'Kazakhstani tenge', 'Asia'),
('Kenya', 'KE', 'KEN', 404, 'Nairobi', 'Kenyan shilling', 'Africa'),
('Kiribati', 'KI', 'KIR', 296, 'South Tarawa', 'Australian dollar', 'Oceania'),
('Kuwait', 'KW', 'KWT', 414, 'Kuwait City', 'Kuwaiti dinar', 'Asia'),
('Kyrgyzstan', 'KG', 'KGZ', 417, 'Bishkek', 'Kyrgyzstani som', 'Asia'),
('Lao Peoples Democratic Republic', 'LA', 'LAO', 418, 'Vientiane', 'Lao kip', 'Asia'),
('Latvia', 'LV', 'LVA', 428, 'Riga', 'Euro', 'Europe'),
('Lebanon', 'LB', 'LBN', 422, 'Beirut', 'Lebanese pound', 'Asia'),
('Lesotho', 'LS', 'LSO', 426, 'Maseru', 'Lesotho loti', 'Africa'),
('Liberia', 'LR', 'LBR', 430, 'Monrovia', 'Liberian dollar', 'Africa'),
('Libya', 'LY', 'LBY', 434, 'Tripoli', 'Libyan dinar', 'Africa'),
('Liechtenstein', 'LI', 'LIE', 438, 'Vaduz', 'Swiss franc', 'Europe'),
('Lithuania', 'LT', 'LTU', 440, 'Vilnius', 'Euro', 'Europe'),
('Luxembourg', 'LU', 'LUX', 442, 'Luxembourg City', 'Euro', 'Europe'),
('Madagascar', 'MG', 'MDG', 450, 'Antananarivo', 'Malagasy ariary', 'Africa'),
('Malawi', 'MW', 'MWI', 454, 'Lilongwe', 'Malawian kwacha', 'Africa'),
('Malaysia', 'MY', 'MYS', 458, 'Kuala Lumpur', 'Malaysian ringgit', 'Asia'),
('Maldives', 'MV', 'MDV', 462, 'Male', 'Maldivian rufiyaa', 'Asia'),
('Mali', 'ML', 'MLI', 466, 'Bamako', 'West African CFA franc', 'Africa'),
('Malta', 'MT', 'MLT', 470, 'Valletta', 'Euro', 'Europe'),
('Marshall Islands', 'MH', 'MHL', 584, 'Majuro', 'United States dollar', 'Oceania'),
('Martinique', 'MQ', 'MTQ', 474, 'Fort-de-France', 'Euro', 'North America'),
('Mauritania', 'MR', 'MRT', 478, 'Nouakchott', 'Mauritanian ouguiya', 'Africa'),
('Mauritius', 'MU', 'MUS', 480, 'Port Louis', 'Mauritian rupee', 'Africa'),
('Mexico', 'MX', 'MEX', 484, 'Mexico City', 'Mexican peso', 'North America'),
('Micronesia (Federated States of)', 'FM', 'FSM', 583, 'Palikir', 'United States dollar', 'Oceania'),
('Moldova (Republic of)', 'MD', 'MDA', 498, 'Chișinău', 'Moldovan leu', 'Europe'),
('Monaco', 'MC', 'MCO', 492, 'Monaco', 'Euro', 'Europe'),
('Mongolia', 'MN', 'MNG', 496, 'Ulaanbaatar', 'Mongolian tögrög', 'Asia'),
('Montenegro', 'ME', 'MNE', 499, 'Podgorica', 'Euro', 'Europe'),
('Montserrat', 'MS', 'MSR', 500, 'Plymouth', 'Eastern Caribbean dollar', 'North America'),
('Morocco', 'MA', 'MAR', 504, 'Rabat', 'Moroccan dirham', 'Africa'),
('Mozambique', 'MZ', 'MOZ', 508, 'Maputo', 'Mozambican metical', 'Africa'),
('Myanmar', 'MM', 'MMR', 104, 'Naypyidaw', 'Burmese kyat', 'Asia'),
('Namibia', 'NA', 'NAM', 516, 'Windhoek', 'Namibian dollar', 'Africa'),
('Nauru', 'NR', 'NRU', 520, 'Yaren', 'Australian dollar', 'Oceania'),
('Nepal', 'NP', 'NPL', 524, 'Kathmandu', 'Nepalese rupee', 'Asia'),
('Netherlands', 'NL', 'NLD', 528, 'Amsterdam', 'Euro', 'Europe'),
('New Caledonia', 'NC', 'NCL', 540, 'Nouméa', 'CFP franc', 'Oceania'),
('New Zealand', 'NZ', 'NZL', 554, 'Wellington', 'New Zealand dollar', 'Oceania'),
('Nicaragua', 'NI', 'NIC', 558, 'Managua', 'Nicaraguan córdoba', 'North America'),
('Niger', 'NE', 'NER', 562, 'Niamey', 'West Africa')
('Nigeria', 'NG', 'NGA', 566, 'Abuja', 'Nigerian naira', 'Africa'),
('Niue', 'NU', 'NIU', 570, 'Alofi', 'New Zealand dollar', 'Oceania'),
('Norfolk Island', 'NF', 'NFK', 574, 'Kingston', 'Australian dollar', 'Oceania'),
('North Macedonia', 'MK', 'MKD', 807, 'Skopje', 'Macedonian denar', 'Europe'),
('Northern Mariana Islands', 'MP', 'MNP', 580, 'Saipan', 'United States dollar', 'Oceania'),
('Norway', 'NO', 'NOR', 578, 'Oslo', 'Norwegian krone', 'Europe'),
('Oman', 'OM', 'OMN', 512, 'Muscat', 'Omani rial', 'Asia'),
('Pakistan', 'PK', 'PAK', 586, 'Islamabad', 'Pakistani rupee', 'Asia'),
('Palau', 'PW', 'PLW', 585, 'Ngerulmud', 'United States dollar', 'Oceania'),
('Palestine, State of', 'PS', 'PSE', 275, 'Ramallah', 'Israeli new shekel', 'Asia'),
('Panama', 'PA', 'PAN', 591, 'Panama City', 'Panamanian balboa', 'North America'),
('Papua New Guinea', 'PG', 'PNG', 598, 'Port Moresby', 'Papua New Guinean kina', 'Oceania'),
('Paraguay', 'PY', 'PRY', 600, 'Asunción', 'Paraguayan guaraní', 'South America'),
('Peru', 'PE', 'PER', 604, 'Lima', 'Peruvian sol', 'South America'),
('Philippines', 'PH', 'PHL', 608, 'Manila', 'Philippine peso', 'Asia'),
('Pitcairn', 'PN', 'PCN', 612, 'Adamstown', 'New Zealand dollar', 'Oceania'),
('Poland', 'PL', 'POL', 616, 'Warsaw', 'Polish złoty', 'Europe'),
('Portugal', 'PT', 'PRT', 620, 'Lisbon', 'Euro', 'Europe'),
('Puerto Rico', 'PR', 'PRI', 630, 'San Juan', 'United States dollar', 'North America'),
('Qatar', 'QA', 'QAT', 634, 'Doha', 'Qatari riyal', 'Asia'),
('Réunion', 'RE', 'REU', 638, 'Saint-Denis', 'Euro', 'Africa'),
('Romania', 'RO', 'ROU', 642, 'Bucharest', 'Romanian leu', 'Europe'),
('Russian Federation', 'RU', 'RUS', 643, 'Moscow', 'Russian ruble', 'Europe'),
('Rwanda', 'RW', 'RWA', 646, 'Kigali', 'Rwandan franc', 'Africa'),
('Saint Barthélemy', 'BL', 'BLM', 652, 'Gustavia', 'Euro', 'North America'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654, 'Jamestown', 'Saint Helena pound', 'Africa'),
('Saint Lucia', 'LC', 'LCA', 662, 'Castries', 'East Caribbean dollar', 'North America'),
('Saint Martin (French part)', 'MF', 'MAF', 663, 'Marigot', 'Euro', 'North America'),
('Saint Pierre and Miquelon', 'PM', 'SPM', 666, 'Saint-Pierre', 'Euro', 'North America'),
('Saint Vincent and the Grenadines', 'VC', 'VCT', 670, 'Kingstown', 'East Caribbean dollar', 'North America'),
('Samoa', 'WS', 'WSM', 882, 'Apia', 'Samoan tālā', 'Oceania'),
('San Marino', 'SM', 'SMR', 674, 'City of San Marino', 'Euro', 'Europe'),
('Sao Tome and Principe', 'ST', 'STP', 678, 'São Tomé', 'São Tomé and Príncipe dobra', 'Africa'),
('Saudi Arabia', 'SA', 'SAU', 682, 'Riyadh', 'Saudi riyal', 'Asia'),
('Senegal', 'SN', 'SEN', 686, 'Dakar', 'West African CFA franc', 'Africa'),
('Serbia', 'RS', 'SRB', 688, 'Belgrade', 'Serbian dinar', 'Europe'),
('Seychelles', 'SC', 'SYC', 690, 'Victoria', 'Seychellois rupee', 'Africa'),
('Sierra Leone', 'SL', 'SLE', 694, 'Freetown', 'Sierra Leonean leone', 'Africa'),
('Singapore', 'SG', 'SGP', 702, 'Singapore', 'Singapore dollar', 'Asia'),
('Sint Maarten (Dutch part)', 'SX', 'SXM', 534, 'Philipsburg', 'Netherlands Antillean guilder', 'North America'),
('Slovakia', 'SK', 'SVK', 703, 'Bratislava', 'Euro', 'Europe'),
('Slovenia', 'SI', 'SVN', 705, 'Ljubljana', 'Euro', 'Europe'),
('Solomon Islands', 'SB', 'SLB', 90, 'Honiara', 'Solomon Islands dollar', 'Oceania'),
('Somalia', 'SO', 'SOM', 706, 'Mogadishu', 'Somali shilling', 'Africa'),
('South Africa', 'ZA', 'ZAF', 710, 'Pretoria', 'South African rand', 'Africa'),
('South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, 'King Edward Point', 'British pound', 'Antarctica'),
('South Sudan', 'SS', 'SSD', 728, 'Juba', 'South Sudanese pound', 'Africa'),
('Spain', 'ES', 'ESP', 724, 'Madrid', 'Euro', 'Europe'),
('Sri Lanka', 'LK', 'LKA', 144, 'Colombo', 'Sri Lankan rupee', 'Asia'),
('Sudan', 'SD', 'SDN', 729, 'Khartoum', 'Sudanese pound', 'Africa'),
('Suriname', 'SR', 'SUR', 740, 'Paramaribo', 'Surinamese dollar', 'South America'),
('Svalbard and Jan Mayen', 'SJ', 'SJM', 744, 'Longyearbyen', 'Norwegiankrone', 'Europe'),
('Sweden', 'SE', 'SWE', 752, 'Stockholm', 'Swedish krona', 'Europe'),
('Switzerland', 'CH', 'CHE', 756, 'Bern', 'Swiss franc', 'Europe'),
('Syrian Arab Republic', 'SY', 'SYR', 760, 'Damascus', 'Syrian pound', 'Asia'),
('Taiwan, Province of China', 'TW', 'TWN', 158, 'Taipei', 'New Taiwan dollar', 'Asia'),
('Tajikistan', 'TJ', 'TJK', 762, 'Dushanbe', 'Tajikistani somoni', 'Asia'),
('Tanzania, United Republic of', 'TZ', 'TZA', 834, 'Dodoma', 'Tanzanian shilling', 'Africa'),
('Thailand', 'TH', 'THA', 764, 'Bangkok', 'Thai baht', 'Asia'),
('Timor-Leste', 'TL', 'TLS', 626, 'Dili', 'United States dollar', 'Asia'),
('Togo', 'TG', 'TGO', 768, 'Lomé', 'West African CFA franc', 'Africa'),
('Tokelau', 'TK', 'TKL', 772, 'Fakaofo', 'New Zealand dollar', 'Oceania'),
('Tonga', 'TO', 'TON', 776, "Nuku'alofa", "Tongan paʻanga", 'Oceania'),
('Trinidad and Tobago', 'TT', 'TTO', 780, 'Port of Spain', 'Trinidad and Tobago dollar', 'North America'),
('Tunisia', 'TN', 'TUN', 788, 'Tunis', 'Tunisian dinar', 'Africa'),
('Turkey', 'TR', 'TUR', 792, 'Ankara', 'Turkish lira', 'Asia'),
('Turkmenistan', 'TM', 'TKM', 795, 'Ashgabat', 'Turkmenistan manat', 'Asia'),
('Turks and Caicos Islands', 'TC', 'TCA', 796, 'Cockburn Town', 'United States dollar', 'North America'),
('Tuvalu', 'TV', 'TUV', 798, 'Funafuti', 'Australian dollar', 'Oceania'),
('Uganda', 'UG', 'UGA', 800, 'Kampala', 'Ugandan shilling', 'Africa'),
('Ukraine', 'UA', 'UKR', 804, 'Kyiv', 'Ukrainian hryvnia', 'Europe'),
('United Arab Emirates', 'AE', 'ARE', 784, 'Abu Dhabi', 'United Arab Emirates dirham', 'Asia'),
('United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 826, 'London', 'British pound', 'Europe'),
('United States of America', 'US', 'USA', 840, 'Washington, D.C.', 'United States dollar', 'North America'),
('United States Minor Outlying Islands', 'UM', 'UMI', 581, '', 'United States dollar', 'Oceania'),
('Uruguay', 'UY', 'URY', 858, 'Montevideo', 'Uruguayan peso', 'South America'),
('Uzbekistan', 'UZ', 'UZB', 860, 'Tashkent', "Uzbekistani so'm", 'Asia'),
('Vanuatu', 'VU', 'VUT',548, 'Port Vila', 'Vanuatu vatu', 'Oceania'),
('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 862, 'Caracas', 'Venezuelan bolívar', 'South America'),
('Viet Nam', 'VN', 'VNM', 704, 'Hanoi', 'Vietnamese đồng', 'Asia'),
('Virgin Islands (British)', 'VG', 'VGB', 92, 'Road Town', 'United States dollar', 'North America'),
('Virgin Islands (U.S.)', 'VI', 'VIR', 850, 'Charlotte Amalie', 'United States dollar', 'North America'),
('Wallis and Futuna', 'WF', 'WLF', 876, 'Mata-Utu', 'CFP franc', 'Oceania'),
('Western Sahara', 'EH', 'ESH', 732, 'El Aaiún', 'Moroccan dirham', 'Africa'),
('Yemen', 'YE', 'YEM', 887, "Sana'a", 'Yemeni rial', 'Asia'),
('Zambia', 'ZM', 'ZMB', 894, 'Lusaka', 'Zambian kwacha', 'Africa'),
('Zimbabwe', 'ZW', 'ZWE', 716, 'Harare', 'United States dollar', 'Africa'),
ON CONFLICT DO NOTHING;